// api/telegram.js
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const TG = (method) => `https://api.telegram.org/bot${process.env.TELEGRAM_BOT_TOKEN}/${method}`;

async function tgSendMessage(chat_id, text, reply_markup) {
  const payload = { chat_id, text, parse_mode: "HTML" };
  if (reply_markup) payload.reply_markup = reply_markup;
  await fetch(TG("sendMessage"), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
}
async function tgAnswerCallbackQuery(callback_query_id) {
  await fetch(TG("answerCallbackQuery"), { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ callback_query_id }) });
}
function mainMenuKeyboard() { return { inline_keyboard: [[{ text: "🎓 Acceder al grupo de Telegram P44", callback_data: "acceso_grupo" }],[{ text: "❓ Escribir mensaje a Miguel", url: "https://t.me/Miguel_ACRAPOL" }]] }; }
function shareContactKeyboard() { return { keyboard: [[{ text: "📱 Enviar mi contacto", request_contact: true }]], resize_keyboard: true, is_persistent: true }; }
function removeKeyboard() { return { remove_keyboard: true }; }
async function getOrCreateUser(telegram_user_id, username) {
  const { data: existing } = await supabase.from("telegram_onboarding_p44").select("*").eq("telegram_user_id", telegram_user_id).maybeSingle();
  if (existing) return existing;
  const { data: created, error } = await supabase.from("telegram_onboarding_p44").insert({ telegram_user_id, username, estado: "menu" }).select("*").single();
  if (error) throw error; return created;
}
async function updateUser(telegram_user_id, patch) {
  const { error } = await supabase.from("telegram_onboarding_p44").update({ ...patch, ultima_interaccion: new Date().toISOString() }).eq("telegram_user_id", telegram_user_id);
  if (error) throw error;
}
function isValidLinePaso2(text) { const parts = text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean); if (parts.length !== 3) return false; const email=parts[1]; return email.includes("@") && email.length>=6; }
function extractPaso2(text) { const [nombre,email,curso]=text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean); return {nombre,email,curso}; }
function msgInicio() { return "👋 Bienvenido a <b>ACRAPOL</b>, la academia que eligen los mejores.\n\nSelecciona una opción, si vas a solicitar acceder al grupo de Telegram hazlo con tu <b><u>teléfono móvil</u></b> 📱\n\nPuedes escribir <b>MENÚ</b> en cualquier momento para volver al inicio."; }
function msgPaso1() { return "Paso 1/5 ✅\n\nDentro del curso <b><u>debes</u></b> realizar estas acciones:\n\n1️⃣ Lectura obligatoria del PDF <b>EXPLICACIÓN DEL CURSO</b>\n2️⃣ Rellenar el <b>FORMULARIO DEL ALUMNO</b> con datos veraces\n3️⃣ Aceptar las <b>CONDICIONES Y NORMAS DE USO</b>\n\nCuando lo hayas hecho todo, escribe: <b>HECHO</b>\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
function msgPaso2() { return "Paso 2/5 ✅\n\nSolicita el acceso al grupo desde el Campus:\n\n1️⃣ Apartado <b>INICIO</b> dentro del Módulo/Curso <b> → “Solicitud de acceso al Grupo P44”</b>;\n\n2️⃣ Se te abrirá la web o app de Telegram → Unirse al grupo o <i>Join group</i>.\n\nCuando lo hayas hecho, escribe: <b>HECHO</b>\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
function msgPaso3() { return "Paso 3/5 ✅\n\nEnvíame tus datos en <b>3 líneas</b>, de esta forma:\n\n<b>Nombre y apellidos</b>\n<b>Correo con el que te has matriculado</b>\n<b>Curso (Total44, Pack 3 Módulos, Intensivo)</b>\n\nEjemplo:\nMiguel García Fernández\nmiguel@acrapol.es\nTotal44\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
function msgPaso4() { return "Paso 4/5 (verificación obligatoria) 📱\n\nAntes de enviarme tu contacto, configura tu teléfono como <b>VISIBLE PARA TODOS</b>:\n\n1️⃣ Telegram → Ajustes\n2️⃣ Privacidad y seguridad\n3️⃣ Número de teléfono\n4️⃣ En “¿Quién puede ver mi número?” selecciona <b>TODOS</b>\n\n✅ Cuando esté en <b>TODOS</b>, vuelve aquí y pulsa el botón:\n<b>📱 Enviar mi contacto</b>\n\nSi no ves el botón, pulsa el icono del <b>teclado</b> abajo en Telegram.\n\n❌ <b>NO</b> uses el clip 📎 → Contacto (abre la agenda y permite enviar otro contacto).\n\nCuando lo envíes correctamente te marcaré ✅\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
function msgPaso5() { return "Paso 5/5 ✅\n\nDatos recibidos correctamente.\n\nMiguel verificará la información y te dará acceso al grupo.\n⏳ Tiempo habitual: menos de 24h.\n\nSi pasado ese tiempo no tienes acceso, escribe: <b>REVISAR</b>\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
function msgYaPendiente() { return "✅ Ya tengo tus datos y tu teléfono.\n\nTu solicitud está <b>pendiente de revisión</b> por un profesor.\nSi han pasado 24h, escribe <b>REVISAR</b>.\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
function msgYaAprobado() { return "✅ Ya estás verificado.\n\nSi aún no tienes acceso al grupo, escribe <b>REVISAR</b>.\n\n(<i>Escribe MENÚ para volver al inicio</i>)"; }
async function notifyTeachers(user, telegram_user_id, username, tg_name) {
  const text = "📥 <b>ALTA TELEGRAM P44 PENDIENTE</b>\n\n"+`👤 Nombre: ${user.nombre??"-"}\n`+`📧 Email: ${user.email??"-"}\n`+`🎓 Curso: ${user.curso??"-"}\n`+`📱 Teléfono: ${user.telefono??"-"}\n`+`🆔 Telegram ID: ${telegram_user_id}\n`+`🔤 Usuario: ${username?"@"+username:`<a href="tg://user?id=${telegram_user_id}">${tg_name||"Abrir perfil"}</a>`}\n\nEstado: Pendiente de verificación`;
  await tgSendMessage(process.env.TEACHERS_CHAT_ID,text);
}
export default async function handler(req,res) {
  if(req.method!=="POST") return res.status(200).send("ok"); const update=req.body;
  if(update.callback_query){ const cq=update.callback_query; await tgAnswerCallbackQuery(cq.id); const chat_id=cq.message.chat.id, telegram_user_id=cq.from.id, username=cq.from.username??null, data=cq.data; const user=await getOrCreateUser(telegram_user_id,username); if(data==="acceso_grupo"){ if(user.acceso_concedido===true||user.estado==="acceso_aprobado"){await tgSendMessage(chat_id,msgYaAprobado());return res.status(200).json({ok:true});} if(user.telefono&&user.estado==="acceso_pendiente_revision"){await tgSendMessage(chat_id,msgYaPendiente());return res.status(200).json({ok:true});} await updateUser(telegram_user_id,{estado:"acceso_p1"});await tgSendMessage(chat_id,msgPaso1());return res.status(200).json({ok:true});} return res.status(200).json({ok:true}); }
  if(!update.message) return res.status(200).json({ok:true}); const msg=update.message, chat_id=msg.chat.id, telegram_user_id=msg.from.id, username=msg.from.username??null, first_name=msg.from.first_name??"", last_name=msg.from.last_name??"", tg_name=`${first_name} ${last_name}`.trim(), text=(msg.text??"").trim(); const user=await getOrCreateUser(telegram_user_id,username);
  if(chat_id.toString()!==process.env.TEACHERS_CHAT_ID?.toString()&&text&&(text.toUpperCase()==="MENU"||text==="/start"||text==="/menu")){await updateUser(telegram_user_id,{estado:"menu"});await tgSendMessage(chat_id,msgInicio(),mainMenuKeyboard());return res.status(200).json({ok:true});}
  if(chat_id.toString()===process.env.TEACHERS_CHAT_ID?.toString()){let t=(text||"").trim();const TU=t.toUpperCase();if(TU.startsWith("APROBADO "))t=`APROBAR ${t.split(" ")[1]}`;if(t.toUpperCase().startsWith("APROBAR ")){const alumnoId=Number(t.split(" ")[1]);if(!Number.isFinite(alumnoId)){await tgSendMessage(chat_id,"Formato: APROBAR <telegram_user_id>");return res.status(200).json({ok:true});}const{error}=await supabase.from("telegram_onboarding_p44").update({acceso_concedido:true,estado:"acceso_aprobado",fecha_acceso:new Date().toISOString(),verificado_por:"PROFESOR"}).eq("telegram_user_id",alumnoId);if(error){await tgSendMessage(chat_id,`❌ Error aprobando: ${error.message}`);return res.status(200).json({ok:true});}await tgSendMessage(alumnoId,"✅ Verificación completada. Ya puedes acceder al grupo. Si aún no lo ves, escribe REVISAR.");await tgSendMessage(chat_id,`✅ Aprobado P44: ${alumnoId}`);return res.status(200).json({ok:true});}if(t.toUpperCase().startsWith("DENEGAR ")){const parts=t.split(" "),alumnoId=Number(parts[1]),motivo=parts.slice(2).join(" ").trim()||"No coincide con la matrícula.";if(!Number.isFinite(alumnoId)){await tgSendMessage(chat_id,"Formato: DENEGAR <telegram_user_id> <motivo opcional>");return res.status(200).json({ok:true});}const{error}=await supabase.from("telegram_onboarding_p44").update({acceso_concedido:false,estado:"acceso_denegado",fecha_verificacion:new Date().toISOString(),verificado_por:"PROFESOR",notas:motivo}).eq("telegram_user_id",alumnoId);if(error){await tgSendMessage(chat_id,`❌ Error denegando: ${error.message}`);return res.status(200).json({ok:true});}await tgSendMessage(alumnoId,`❌ Verificación no aprobada: ${motivo}\nSi crees que es un error, escribe REVISAR.`);await tgSendMessage(chat_id,`❌ Denegado P44: ${alumnoId} — ${motivo}`);return res.status(200).json({ok:true});}await tgSendMessage(chat_id,"Comandos P44:\n✅ APROBAR <telegram_user_id>\n❌ DENEGAR <telegram_user_id> <motivo opcional>");return res.status(200).json({ok:true});}
  if(chat_id.toString()!==process.env.TEACHERS_CHAT_ID?.toString()&&(text.toUpperCase()==="REVISAR"||text==="/revisar")){const aviso="🔔 <b>REVISAR ACCESO P44</b>\n\n"+`🆔 Telegram ID: ${telegram_user_id}\n`+`🔤 Usuario: ${username?"@"+username:"-"}\n`+`📱 Teléfono: ${user.telefono??"-"}\n`+`📧 Email: ${user.email??"-"}\n`+`🎓 Curso: ${user.curso??"-"}\n`;await tgSendMessage(process.env.TEACHERS_CHAT_ID,aviso);await tgSendMessage(chat_id,"Perfecto ✅ He avisado al profesor para que revise tu acceso.");return res.status(200).json({ok:true});}
  if(user.estado==="acceso_p1"){if(text.toUpperCase()==="HECHO"){await updateUser(telegram_user_id,{estado:"acceso_p2"});await tgSendMessage(chat_id,msgPaso2());}else await tgSendMessage(chat_id,"Cuando lo hayas hecho, escribe <b>HECHO</b>.");return res.status(200).json({ok:true});}
  if(user.estado==="acceso_p2"){if(text.toUpperCase()==="HECHO"){await updateUser(telegram_user_id,{estado:"acceso_p3"});await tgSendMessage(chat_id,msgPaso3());}else await tgSendMessage(chat_id,"Cuando lo hayas hecho, escribe <b>HECHO</b>.");return res.status(200).json({ok:true});}
  if(user.estado==="acceso_p3"){if(!isValidLinePaso2(text)){await tgSendMessage(chat_id,"Formato incorrecto. Envíame exactamente 3 líneas. Ejemplo:\nMiguel García Fernández\nmiguel.acrapol@acrapol.es\nTotal44");return res.status(200).json({ok:true});}const{nombre,email,curso}=extractPaso2(text);await updateUser(telegram_user_id,{nombre,email,curso,estado:"acceso_p4"});await tgSendMessage(chat_id,msgPaso4(),shareContactKeyboard());return res.status(200).json({ok:true});}
  if(user.estado==="acceso_p4"){if(msg.contact&&msg.contact.phone_number){if(!msg.contact.user_id||msg.contact.user_id!==telegram_user_id){await tgSendMessage(chat_id,"❌ Ese no es tu contacto.\nPulsa <b>📱 Enviar mi contacto</b> (no vale enviar un contacto desde la agenda).",shareContactKeyboard());return res.status(200).json({ok:true});}await updateUser(telegram_user_id,{telefono:msg.contact.phone_number,estado:"acceso_pendiente_revision"});const refreshed=await getOrCreateUser(telegram_user_id,username);await tgSendMessage(chat_id,"Contacto recibido ✅",removeKeyboard());await tgSendMessage(chat_id,msgPaso5());await notifyTeachers(refreshed,telegram_user_id,username,tg_name);return res.status(200).json({ok:true});}await tgSendMessage(chat_id,"Pulsa <b>📱 Enviar mi contacto</b> (y asegúrate de tener “¿Quién puede ver mi número?” en <b>TODOS</b>).",shareContactKeyboard());return res.status(200).json({ok:true});}
  await tgSendMessage(chat_id,msgInicio(),mainMenuKeyboard());return res.status(200).json({ok:true});
}
